### ISSUE TITLE
Improve contrast with icons/text in footer

### ISSUE THREAD

**Issue by clairehelland** [andreamartz/mmc-authentic-grace#42]
Adjust colors.

**Comment by andreamartz** [comment]
Two resources that might help:
https://stackoverflow.com/questions/26516353/font-awesome-background-color
https://fontawesome.com/how-to-use/on-the-web/styling/stacking-icons

**Comment by andreamartz** [comment]
The two resources above were almost exactly what we needed.  There was a very slight alignment issue between the background circle and the icon, and I didn't see a way to fix it.

**Comment by andreamartz** [comment]
I ended up just changing font colors and the section color of the footer area.  The contrast issue is much better now, but I still wish I could make the "fill in" color white (for example the "f" in the Facebook icon).

**Comment by andreamartz** [comment]
Addressed in PR #49
